let suggestions = [
    "Channel",
    "Coding",
    "Deutschland",
    "YouTube",
    "YouTuber",
    "YouTube Channel",
    "Blogger",
    "Hollywood",
    "Vlogger",
    "Twitter",
    "Hotmail",
    "Hoparlör",
    "horoz",
    "horror",
    "Taksi",
    "Facebook",
    "Freelancer",
    "Facebook Page",
    "Designer",
    "Developer",
    "Web Designer",
    "Web Developer",
    "Login Form in HTML & CSS",
    "How to learn HTML & CSS",
    "How to learn JavaScript",
    "How to learn Java",
    "How to learn C#",
    "How to became Freelancer",
    "How to became Web Designer",
    "How to start Gaming Channel",
    "How to start YouTube Channel",
    "What does HTML stands for?",
    "What does CSS stands for?",
];